export declare let employeeData: Object[];
export declare let summaryRowData: Object[];
export declare let summaryData: object[];
export declare let sampleData: Object[];
export declare let dragData: Object[];
export declare let textWrapData: Object[];
export declare let textdata: Object[];
export declare let headerData: Object[];
export declare let stackedData: Object[];
export declare let formatData: Object[];
export declare let sortData: Object[];
export declare let lockRowDropDownData: number[];
export declare let projectData: Object[];
export declare let lineData: Object[];
export declare let columnData: Object[];
export declare let getSparkData: Function;
export declare let treesampleData: Object[];
export declare let countries: Object[];
export declare let virtualData: Object[];
export declare function dataSource(): void;
export declare let getTradeData: object[];
interface FoodMenuItem {
    FoodId: number;
    CategoryId?: number | null;
    FoodName: string;
    FoodCategory: string;
    FoodType: string;
    newPrice: number;
    originalPrice: number;
    Image: string;
    Rating: number;
    TotalReviews: number;
    FoodDescription: string;
    IsBestseller: boolean;
    vegCount: number;
    nonvegCount: number;
    ingredients: string[];
}
export declare let foodMenu: FoodMenuItem[];
export declare let wrapData: object[];
export declare let rowSpanData: object[];
export {};
