import { loadCultureFiles } from '../common/culture-loader';
import { DocumentEditorContainer, Ribbon, Toolbar } from '@syncfusion/ej2-documenteditor';
import { TitleBar } from './title-bar';
import { L10n } from '@syncfusion/ej2-base';
import * as data from './data-right-to-left.json';

//Document Editor Arabic Sample Locale
L10n.load({
    'ar-AE': {
        'documenteditor': {
            'Table': 'الجدول',
            'Row': 'الصف',
            'Cell': 'الخليه',
            'Ok': 'موافق',
            'Cancel': 'إلغاء الأمر',
            'Size': 'حجم',
            'Preferred Width': 'العرض المفضل',
            'Points': 'نقاط',
            'Percent': 'المائه',
            'Measure in': 'القياس في',
            'Alignment': 'محاذاه',
            'Left': 'اليسار',
            'Center': 'مركز',
            'Right': 'الحق',
            'Justify': 'تبرير',
            'Indent from left': 'مسافة بادئه من اليسار',
            'Borders and Shading': 'الحدود والتظليل',
            'Options': 'خيارات',
            'Specify height': 'تحديد الارتفاع',
            'At least': 'الاقل',
            'Exactly': 'تماما',
            'Row height is': 'ارتفاع الصف هو',
            'Allow row to break across pages': 'السماح للصف بالخروج عبر الصفحات',
            'Repeat as header row at the top of each page': 'تكرار كصف راس في اعلي كل صفحه',
            'Vertical alignment': 'محاذاة عموديه',
            'Top': 'أعلى',
            'Bottom': 'اسفل',
            'Default cell margins': 'هوامش الخلية الافتراضية',
            'Default cell spacing': 'تباعد الخلايا الافتراضي',
            'Allow spacing between cells': 'السماح بالتباعد بين الخلايا',
            'Cell margins': 'هوامش الخلية',
            'Same as the whole table': 'نفس الجدول بأكمله',
            'Borders': 'الحدود',
            'None': 'اي',
            'Style': 'نمط',
            'Width': 'عرض',
            'Height': 'ارتفاع',
            'Letter': 'رساله',
            'Tabloid': 'التابلويد',
            'Legal': 'القانونيه',
            'Statement': 'بيان',
            'Executive': 'التنفيذي',
            'A3': 'A3',
            'A4': 'A4',
            'A5': 'A5',
            'B4': 'B4',
            'B5': 'B5',
            'Custom Size': 'حجم مخصص',
            'Different odd and even': 'مختلفه غريبه وحتى',
            'Different first page': 'صفحه اولي مختلفه',
            'From edge': 'من الحافة',
            'Header': 'راس',
            'Footer': 'تذييل الصفحه',
            'Margin': 'الهوامش',
            'Paper': 'الورق',
            'Layout': 'تخطيط',
            'Orientation': 'التوجه',
            'Landscape': 'المناظر الطبيعيه',
            'Portrait': 'صوره',
            'Show page numbers': 'إظهار أرقام الصفحات',
            'Right align page numbers': 'محاذاة أرقام الصفحات إلى اليمين',
            'Nothing': 'شيء',
            'Tab leader': 'قائد علامة التبويب',
            'Show levels': 'إظهار المستويات',
            'Use hyperlinks instead of page numbers': 'استخدام الارتباطات التشعبية بدلا من أرقام الصفحات',
            'Build table of contents from': 'إنشاء جدول محتويات من',
            'Styles': 'انماط',
            'Available styles': 'الأنماط المتاحة',
            'TOC level': 'مستوي جدول المحتويات',
            'Heading': 'عنوان',
            'Heading 1': 'العنوان 1',
            'Heading 2': 'العنوان 2',
            'Heading 3': 'العنوان 3',
            'Heading 4': 'العنوان 4',
            'Heading 5': 'العنوان 5',
            'Heading 6': 'العنوان 6',
            'List Paragraph': 'قائمه الفقرة',
            'Normal': 'العاديه',
            'Outline levels': 'مستويات المخطط التفصيلي',
            'Table entry fields': 'حقول إدخال الجدول',
            'Modify': 'تعديل',
            'Color': 'لون',
            'Setting': 'اعداد',
            'Box': 'مربع',
            'All': 'جميع',
            'Custom': 'المخصصه',
            'Preview': 'معاينه',
            'Shading': 'التظليل',
            'Fill': 'ملء',
            'Apply To': 'تنطبق علي',
            'Table Properties': 'خصائص الجدول',
            'Cell Options': 'خيارات الخلية',
            'Table Options': 'خيارات الجدول',
            'Insert Table': 'ادراج جدول',
            'Number of columns': 'عدد الاعمده',
            'Number of rows': 'عدد الصفوف',
            'Text to display': 'النص الذي سيتم عرضه',
            'Address': 'عنوان',
            'Insert Hyperlink': 'ادراج ارتباط تشعبي',
            'Edit Hyperlink': 'تحرير ارتباط تشعبي',
            'Insert': 'ادراج',
            'General': 'العامه',
            'Indentation': 'المسافه البادئه',
            'Before text': 'قبل النص',
            'Special': 'الخاصه',
            'First line': 'السطر الأول',
            'Hanging': 'معلقه',
            'After text': 'بعد النص',
            'By': 'من قبل',
            'Before': 'قبل',
            'Line Spacing': 'تباعد الأسطر',
            'After': 'بعد',
            'At': 'في',
            'Multiple': 'متعدده',
            'Spacing': 'تباعد',
            'Define new Multilevel list': 'تعريف قائمه متعددة الاصعده جديده',
            'List level': 'مستوي القائمة',
            'Choose level to modify': 'اختيار مستوي لتعديل',
            'Level': 'مستوي',
            'Number format': 'تنسيق الأرقام',
            'Number style for this level': 'نمط الرقم لهذا المستوي',
            'Enter formatting for number': 'إدخال تنسيق لرقم',
            'Start at': 'أبدا في',
            'Restart list after': 'أعاده تشغيل القائمة بعد',
            'Position': 'موقف',
            'Text indent at': 'المسافة البادئة للنص في',
            'Aligned at': 'محاذاة في',
            'Follow number with': 'اتبع الرقم مع',
            'Tab character': 'حرف علامة التبويب',
            'Space': 'الفضاء',
            'Arabic': 'العربية',
            'UpRoman': 'UpRoman',
            'LowRoman': 'لورومان',
            'UpLetter': 'الوصلة الصاعدة',
            'LowLetter': 'الحرف المنخفض',
            'Number': 'عدد',
            'Leading zero': 'الصفر الرئيسي',
            'Bullet': 'رصاصه',
            'Ordinal': 'الترتيبيه',
            'Ordinal Text': 'النص الترتيبي',
            'For East': 'للشرق',
            'No Restart': 'لا أعاده تشغيل',
            'Font': 'الخط',
            'Font style': 'نمط الخط',
            'Underline style': 'نمط التسطير',
            'Font color': 'لون الخط',
            'Effects': 'الاثار',
            'Strikethrough': 'يتوسطه',
            'Superscript': 'مرتفع',
            'Subscript': 'منخفض',
            'Double strikethrough': 'يتوسطه خط مزدوج',
            'Regular': 'العاديه',
            'Bold': 'جريئه',
            'Italic': 'مائل',
            'Cut': 'قطع',
            'Copy': 'نسخ',
            'Paste': 'لصق',
            'Hyperlink': 'الارتباط التشعبي',
            'Open Hyperlink': 'فتح ارتباط تشعبي',
            'Copy Hyperlink': 'نسخ ارتباط تشعبي',
            'Remove Hyperlink': 'أزاله ارتباط تشعبي',
            'Paragraph': 'الفقره',
            'Linked Style': 'مرتبط (فقره وحرف)',
            'Character': 'حرف',
            'Merge Cells': 'دمج الخلايا',
            'Insert Above': 'ادراج أعلاه',
            'Insert Below': 'تدرج أدناه',
            'Insert Left': 'ادراج إلى اليسار',
            'Insert Right': 'ادراج اليمين',
            'Delete': 'حذف',
            'Delete Table': 'حذف جدول',
            'Delete Row': 'حذف الصف',
            'Delete Column': 'حذف العمود',
            'File Name': 'اسم الملف',
            'Format Type': 'نوع التنسيق',
            'Save': 'حفظ',
            'Navigation': 'التنقل',
            'Results': 'نتائج',
            'Replace': 'استبدال',
            'Replace All': 'استبدال الكل',
            'We replaced all': 'لقد استبدلنا جميع',
            'Find': 'العثور',
            'No matches': 'لا توجد تطابقات',
            'All Done': 'جميع الإنجازات',
            'Result': 'نتيجه',
            'of': 'من',
            'instances': 'الحالات',
            'with': 'مع',
            'Click to follow link': 'انقر لمتابعه الرابط',
            'Continue Numbering': 'متابعه الترقيم',
            'Bookmark name': 'اسم الاشاره المرجعية',
            'Close': 'اغلاق',
            'Restart At': 'أعاده التشغيل في',
            'Properties': 'خصائص',
            'Name': 'اسم',
            'Style type': 'نوع النمط',
            'Style based on': 'نمط يستند إلى',
            'Style for following paragraph': 'نمط للفقرة التالية',
            'Formatting': 'التنسيق',
            'Numbering and Bullets': 'الترقيم والتعداد النقطي',
            'Numbering': 'ترقيم',
            'Update Field': 'حقل التحديث',
            'Edit Field': 'تحرير الحقل',
            'Bookmark': 'الاشاره المرجعيه',
            'Page Setup': 'اعداد الصفحة',
            'Page Breaks': 'فواصل الصفحة',
            'Section Breaks': 'فواصل القسم',
            'Column': 'عمود',
            'Next Page': 'الصفحة التالية',
            'Continuous': 'الصفحة التالية',
            'No bookmarks found': 'لم يتم العثور علي إشارات مرجعيه',
            'Format': 'تنسيق',
            'Create New Style': 'إنشاء نمط جديد',
            'Modify Style': 'تعديل النمط',
            'New': 'الجديد',
            'Bullets': 'الرصاص',
            'Use bookmarks': 'استخدام الإشارات المرجعية',
            'Table of Contents': 'جدول المحتويات',
            'AutoFit': 'الاحتواء',
            'AutoFit to Contents': 'احتواء تلقائي للمحتويات',
            'AutoFit to Window': 'احتواء تلقائي إلى اطار',
            'Fixed Column Width': 'عرض عمود ثابت',
            'Reset': 'اعاده تعيين',
            'Match case': 'حاله المباراة',
            'Whole words': 'كلمات كامله',
            'Add': 'اضافه',
            'Go To': 'الانتقال إلى',
            'Search for': 'ابحث عن',
            'Replace with': 'استبدال ب',
            'TOC 1': 'جدول المحتويات 1',
            'TOC 2': 'جدول المحتويات 2',
            'TOC 3': 'جدول المحتويات 3',
            'TOC 4': 'جدول المحتويات 4',
            'TOC 5': 'جدول المحتويات 5',
            'TOC 6': 'جدول المحتويات 6',
            'TOC 7': 'جدول المحتويات 7',
            'TOC 8': 'جدول المحتويات 8',
            'TOC 9': 'جدول المحتويات 9',
            'Right-to-left': 'من اليمين إلى اليسار',
            'Left-to-right': 'من اليسار إلى اليمين',
            'Direction': 'الاتجاه',
            'Table direction': 'اتجاه الجدول',
            'Indent from right': 'مسافة بادئه من اليمين',
            'Contextual Spacing': 'عدم أضافه مسافة بين فقرات نفس الأنماط',
            'Password Mismatch': 'كلمه المرور لا  تتطابق',
            'Restrict Editing': 'تقييد التحرير',
            'Formatting restrictions': 'قيود التنسيق',
            'Allow formatting': 'السماح بالتنسيق',
            'Editing restrictions': 'قيود التحرير',
            'Read only': 'للقراءة فقط',
            'Exceptions Optional': 'الاستثناءات (اختياري)',
            'Select Part Of Document And User': 'حدد أجزاء من المستند واختر المستخدمين المسموح لهم  بتحريرها بحريه.',
            'Everyone': 'الجميع',
            'More users': 'المزيد من المستخدمين',
            'Add Users': 'أضافه مستخدمين',
            'Enforcing Protection': 'نعم ، أبدا بفرض الحماية',
            'Start Enforcing Protection': 'بدء فرض الحماية',
            'Enter User': 'ادخل المستخدم',
            'Users': 'المستخدمين',
            'Enter new password': 'ادخل كلمه مرور جديده',
            'Reenter new password to confirm': 'أعد إدخال كلمه مرور جديده للتاكيد',
            'Your permissions': 'الأذونات الخاصة بك',
            'Protected Document': 'هذا المستند محمي من التحرير غير المقصود .  يمكنك التحرير في هذه المنطقة.',
            'You may format text only with certain styles': 'يمكنك تنسيق النص فقط مع أنماط معينه.',
            'Stop Protection': 'إيقاف الحماية',
            'Password': 'كلمه المرور',
            'Spelling Editor': 'محرر الإملاء',
            'Spelling': 'الاملائي',
            'Spell Check': 'التدقيق الإملائي',
            'Underline errors': 'أخطاء التسطير',
            'Ignore': 'تجاهل',
            'Ignore all': 'تجاهل الكل',
            'Add to Dictionary': 'أضافه إلى القاموس',
            'Change': 'تغيير',
            'Change All': 'تغيير الكل',
            'Suggestions': 'اقتراحات',
            'The password is incorrect': 'كلمه المرور غير صحيحه',
            'Error in establishing connection with web server': 'خطا في تاسيس اتصال مع ملقم ويب',
            'Highlight the regions I can edit': 'تسليط الضوء علي المناطق يمكنني تحرير',
            'Show All Regions I Can Edit': 'إظهار كل المناطق التي يمكنني تحريرها',
            'Find Next Region I Can Edit': 'اعثر علي المنطقة التالية التي يمكنني تحريرها',
            'Keep source formatting': 'الاحتفاظ بتنسيق المصدر',
            'Match destination formatting': 'مطابقه تنسيق الوجهة',
            'Text only': 'النص فقط',
            'Comments': 'تعليقات',
            'Type your comment': 'اكتب تعليقك',
            'Post': 'وظيفه',
            'Reply': 'الرد',
            'New Comment': 'تعليق جديد',
            'Edit': 'تحرير',
            'Resolve': 'حل',
            'Reopen': 'فتح',
            'No comments in this document': 'لا توجد تعليقات في هذا المستند',
            'more': 'اكثر',
            'Type your comment here': 'اكتب تعليقك الاستماع',
            'Next Comment': 'التعليق التالي',
            'Previous Comment': 'التعليق السابق',
            'Un-posted comments': 'Un-نشر التعليقات',
            'Discard Comment': 'لم يتم نشر التعليقات المضافة. إذا قمت بالمتابعة ، سيتم تجاهل هذا التعليق.',
            'Drop Down Form Field': 'حقل نموذج منسدل',
            'Drop-down items': 'عناصر منسدلة',
            'Items in drop-down list': 'العناصر في القائمة المنسدلة',
            'ADD': 'أضف',
            'REMOVE': 'إزالة',
            'Field settings': 'الإعدادات الميدانية',
            'Tooltip': 'تلميح',
            'Drop-down enabled': 'تم تمكين القائمة المنسدلة',
            'Check Box Form Field': 'حقل نموذج خانة الاختيار',
            'Check box size': 'حجم خانة الاختيار',
            'Auto': 'تلقاءي',
            'Default value': 'القيمة الافتراضية',
            'Not checked': 'غير مدقق',
            'Checked': 'التحقق',
            'Check box enabled': 'تم تمكين خانة الاختيار',
            'Text Form Field': 'حقل نموذج نصي',
            'Type': 'نوع',
            'Default text': 'النص الافتراضي',
            'Maximum length': 'الحد الأقصى لطول',
            'Text format': 'تنسيق النص',
            'Fill-in enabled': 'تم تمكين التعبئة',
            'Default number': 'الرقم الافتراضي',
            'Default date': 'التاريخ الافتراضي',
            'Date format': 'صيغة التاريخ',
            'Merge Track': 'لن يتم وضع علامة على هذا الإجراء كتغيير. هل تريد الاستمرار?',
            'UnTrack': 'لا يمكن تعقبها',
            'Accept': 'قبول',
            'Reject': 'رفض',
            'Previous Changes': 'التغييرات السابقة',
            'Next Changes': 'التغييرات القادمة',
            'Inserted': 'تم إدراجها',
            'Deleted': 'تم الحذف',
            'Changes': 'التغييرات',
            'Accept all': 'قبول الكل',
            'Reject all': 'رفض الكل',
            'No changes': 'لا تغييرات',
            'Accept Changes': 'قبول التغييرات',
            'Reject Changes': 'رفض التغييرات',
            'User': 'المستعمل',
            'View': 'رأي'
        },
        'documenteditorcontainer': {
            "New": "الجديد",
            "Insert Footnote": "إدراج حاشية",
            "Insert Endnote": "إدراج التعليق الختامي",
            "Footnote Tooltip": "إدراج حاشية سفلية (Alt + Ctrl + F).",
            "Endnote Tooltip": "إدراج التعليق الختامي (Alt + Ctrl + D).",
            "Open": "مفتوح",
            "Undo": "تراجع",
            "Redo": "اعاده",
            "Image": "صورة",
            "Table": "جدول",
            "Link": "رابط",
            "Bookmark": "الاشاره المرجعيه",
            "Table of Contents": "جدول المحتويات",
            "HEADING - - - - 1": "العنوان - - - - 1",
            "HEADING - - - - 2": "العنوان - - - - 2",
            "HEADING - - - - 3": "العنوان - - - - 3",
            "Header": "راس",
            "Footer": "تذييل الصفحه",
            "XML Mapping Pane": "جزء تعيين XML",
            "Page Setup": "إعداد الصفحة",
            "Page Number": "رقم الصفحة",
            "Break": "كسر",
            "Find": "وجد",
            "Local Clipboard": "الحافظة المحلية",
            "Restrict Editing": "تقييد التحرير",
            "Upload from computer": "التحميل من الكمبيوتر",
            "By URL": "حسب عنوان URL",
            "Page": "صفحة",
            "Show properties pane": "إظهار جزء الخصائص",
            "Hide properties pane": "جزء إخفاء الخصائص",
            "Next Page": "الصفحة التالية",
            "Continuous": "مستمر",
            "Header And Footer": "الرأس والتذييل",
            "Options": "خيارات",
            "XML Mapping": "تعيين XML",
            "Custom XML Part:": "جزء XML المخصص:",
            "Core Properties": "الخصائص الأساسية",
            "Levels": "المستويات",
            "Different First Page": "صفحة أولى مختلفة",
            "Different header and footer for odd and even pages": "رأس وتذييل مختلفان للصفحات الفردية والزوجية.",
            "Different Odd And Even Pages": "صفحات فردية وزوجية مختلفة",
            "Different header and footer for first page": "رأس وتذييل مختلفان للصفحة الأولى.",
            "Position": "موضع",
            "Header from Top": "رأس من الأعلى",
            "Footer from Bottom": "تذييل من الأسفل",
            "Distance from top of the page to top of the header": "المسافة من أعلى الصفحة إلى أعلى الرأس.",
            "Distance from bottom of the page to bottom of the footer": "المسافة من أسفل الصفحة إلى أسفل التذييل.",
            "Aspect ratio": "نسبة العرض إلى الارتفاع",
            "W": "W",
            "H": "H",
            "Width": "عرض",
            "Height": "ارتفاع",
            "Text": "نص",
            "Paragraph": "فقرة",
            "Fill": "ملء",
            "Fill color": "لون التعبئة",
            "Border Style": "نمط الحدود",
            "Outside borders": "خارج الحدود",
            "All borders": "جميع الحدود",
            "Inside borders": "داخل الحدود",
            "Left border": "الحدود اليسرى",
            "Inside vertical border": "داخل الحدود الرأسية",
            "Right border": "الحدود اليمنى",
            "Top border": "الحد العلوي",
            "Inside horizontal border": "داخل الحدود الأفقية",
            "Bottom border": "الحد السفلي",
            "Border color": "لون الحدود",
            "Border width": "عرض الحدود",
            "Cell": "خلية",
            "Merge cells": "دمج الخلايا",
            "Insert Or Delete": "إدراج / حذف",
            "Insert columns to the left": "إدراج أعمدة إلى اليسار",
            "Insert columns to the right": "إدراج أعمدة إلى اليمين",
            "Insert rows above": "إدراج الصفوف أعلاه",
            "Insert rows below": "إدراج الصفوف أدناه",
            "Delete rows": "حذف الصفوف",
            "Delete columns": "حذف الأعمدة",
            "Cell Margin": "هامش الخلية",
            "Top": "أعلى",
            "Bottom": "قاع",
            "Left": "يسار",
            "Right": "يمين",
            "Align Text": "محاذاة النص",
            "Align top": "محاذاة الجزء العلوي",
            "Align bottom": "محاذاة القاع",
            "Align center": "محاذاة المركز",
            "Number of heading or outline levels to be shown in table of contents": "عدد مستويات العنوان أو المخطط التفصيلي التي سيتم عرضها في جدول المحتويات.",
            "Show page numbers": "إظهار أرقام الصفحات",
            "Show page numbers in table of contents": "إظهار أرقام الصفحات في جدول المحتويات.",
            "Right align page numbers": "محاذاة أرقام الصفحات لليمين",
            "Right align page numbers in table of contents": "قم بمحاذاة أرقام الصفحات لليمين في جدول المحتويات.",
            "Use hyperlinks": "استخدام الارتباطات التشعبية",
            "Use hyperlinks instead of page numbers": "استخدم الارتباطات التشعبية بدلا من أرقام الصفحات.",
            "Font": "الخط",
            "Font Size": "حجم الخط",
            "Font color": "لون الخط",
            "Text highlight color": "لون تمييز النص",
            "Clear all formatting": "مسح جميع التنسيقات",
            "Bold Tooltip": "غامق (Ctrl+B)",
            "Italic Tooltip": "مائل (Ctrl + I)",
            "Underline Tooltip": "تسطير (Ctrl+U)",
            "Strikethrough": "يتوسطه خط",
            "Superscript Tooltip": "مرتفع (Ctrl+Shift++)",
            "Subscript Tooltip": "نصي منخفض (Ctrl+=)",
            "Align left Tooltip": "محاذاة لليسار (Ctrl+L)",
            "Center Tooltip": "الوسط (Ctrl+E)",
            "Align right Tooltip": "محاذاة لليمين (Ctrl+R)",
            "Justify Tooltip": "الضبط (Ctrl+J)",
            "Decrease indent": "تقليل المسافة البادئة",
            "Increase indent": "زيادة المسافة البادئة",
            "Line spacing": "تباعد الأسطر",
            "Bullets": "رصاص",
            "Numbering": "ترقيم",
            "Styles": "انماط",
            "Manage Styles": "إدارة الأنماط",
            "of": "من",
            "Fit one page": "تناسب صفحة واحدة",
            "Spell Check": "التدقيق الإملائي",
            "Spelling": "هجاء",
            "Underline errors": "تسطير الأخطاء",
            "Fit page width": "ملاءمة عرض الصفحة",
            "Update": "تحديث",
            "Cancel": "إلغاء الأمر",
            "Insert": "أدخل",
            "No Border": "لا حدود",
            "Create a new document": "إنشاء مستند جديد.",
            "Open a document": "افتح مستندا.",
            "Undo Tooltip": "التراجع عن العملية الأخيرة (Ctrl+Z).",
            "Redo Tooltip": "أعد العملية الأخيرة (Ctrl+Y).",
            "Insert inline picture from a file": "إدراج صورة مضمنة من ملف.",
            "Insert a table into the document": "إدراج جدول في المستند",
            "Create Hyperlink": "قم بإنشاء ارتباط في المستند للوصول السريع إلى صفحات الويب والملفات (Ctrl+K).",
            "Insert a bookmark in a specific place in this document": "إدراج إشارة مرجعية في مكان معين في هذا المستند.",
            "Provide an overview of your document by adding a table of contents": "قم بتوفير نظرة عامة على المستند عن طريق إضافة جدول محتويات.",
            "Add or edit the header": "أضف العنوان أو عدله.",
            "Add or edit the footer": "إضافة التذييل أو تحريره.",
            "Open the page setup dialog": "افتح مربع حوار إعداد الصفحة.",
            "Content Control": "التحكم في المحتوى",
            "Insert Content Control": "إدراج عنصر تحكم المحتوى",
            "Add page numbers": "إضافة أرقام الصفحات.",
            "Find Text": "البحث عن نص في المستند (Ctrl+F).",
            "Replace Text": "استبدال النص في المستند (Ctrl+H).",
            "Toggle between the internal clipboard and system clipboard": "قم بالتبديل بين الحافظة الداخلية وحافظة النظام.</br>",
            "Current Page Number": "رقم الصفحة الحالي في المستند. انقر أو اضغط للتنقل في صفحة معينة.",
            "Read only": "للقراءة فقط",
            "Protections": "الحمايه",
            "Error in establishing connection with web server": "خطأ في إنشاء اتصال بخادم الويب",
            "Single": "واحد",
            "Double": "مزدوج",
            "New comment": "تعليق جديد",
            "Comments": "التعليقات",
            "Print layout": "تخطيط الطباعة",
            "Web layout": "تخطيط الويب",
            "Form Fields": "حقول النموذج",
            "Text Form": "نموذج النص",
            "Check Box": "خانة الاختيار",
            "DropDown": "القائمة المنسدلة",
            "Update Fields": "تحديث الحقول",
            "Update cross reference fields": "تحديث حقول الإسناد الترافقي",
            "Track Changes": "تتبع التغييرات التي تم إجراؤها في المستند",
            "TrackChanges": "تتبع التغييرات",
            "AllCaps": "كل الكابس",
            "Change case Tooltip": "تغيير الحالة",
            "UPPERCASE": "الاحرف الكبيره",
            "SentenceCase": "حالة الجملة",
            "Lowercase": "صغيره",
            "CapitalizeEachWord": "كتابة كل كلمة بأحرف كبيرة",
            "ToggleCase": "tOGGLE cASE",
            "No color": "لا لون",
            "Top margin": "الهامش العلوي",
            "Bottom margin": "الهامش السفلي",
            "Left margin": "الهامش الأيسر",
            "Right margin": "الهامش الأيمن",
            "Normal": "عادي",
            "Heading": "عنوان",
            "Heading 1": "العنوان 1",
            "Heading 2": "العنوان 2",
            "Heading 3": "العنوان 3",
            "Heading 4": "الرأس 4",
            "Heading 5": "الرأس 5",
            "Heading 6": "الرأس 6",
            "Heading 7": "الرأس 7",
            "Heading 8": "العنوان 8",
            "Heading 9": "الرأس 9",
            "ZoomLevelTooltip": "مستوى التكبير. انقر أو اضغط لفتح خيارات التكبير/التصغير.",
            "None": "اي",
            "Borders": "الحدود",
            "ShowHiddenMarks Tooltip": "إظهار الأحرف المخفية مثل المسافات وعلامات التبويب وعلامات الفقرات والفواصل (Ctrl + *)",
            "Columns": "الاعمده",
            "Column": "عمود",
            "Page Breaks": "فواصل الصفحات",
            "Section Breaks": "المقطعيه",
            "Link to Previous": "رابط إلى السابق",
            "Link to PreviousTooltip": "ربط هذا القسم برأس القسم السابق أو تذييل",
            "Alternate Text": "نص بديل",
            "The address of this site is not valid. Check the address and try again.": "عنوان هذا الموقع غير صالح. تحقق من العنوان وحاول مرة أخرى.",
            "OK": "موافق",
            "Information": "معلومات",
            "Rich Text Content Control": "التحكم في محتوى النص المنسق",
            "Plain Text Content Control": "التحكم في محتوى النص العادي",
            "Picture Content Control": "التحكم في محتوى الصورة",
            "Combo Box Content Control": "التحكم في محتوى صندوق التحرير والسرد",
            "Drop-Down List Content Control": "التحكم في محتوى القائمة المنسدلة",
            "Date Picker Content Control": "التحكم في محتوى منتقي التاريخ",
            "Check Box Content Control": "التحكم في محتوى خانة الاختيار",
            "Header & Footer": "الرأس والتذييل",
            "Comment": "التعليق",
            "Links": "الصلات",
            "Illustrations": "الرسوم التوضيحيه",
            "Tables": "المناضد",
            "Home": "وطن",
            "Cut": "قص",
            "Copy": "نسخ",
            "Replace": "استبدل",
            "Clipboard": "حافظة",
            "Views": "طرق عرض",
            "Zoom": "التكبير",
            "Zoom In": "تكبير",
            "Zoom Out": "التصغير",
            "One Page": "صفحة واحدة",
            "Page Width": "عرض الصفحة",
            "Show": "عرض",
            "Ruler": "حاكم",
            "Show Bookmark Markers": "إظهار علامات الإشارات المرجعية",
            "View": "منظر",
            "Page Numbers": "أرقام الصفحات",
            "Insert automatic page numbering": "إدراج ترقيم الصفحات تلقائيا",
            "Previous Section": "القسم السابق",
            "Next Section": "القسم التالي",
            "Navigation": "ملاحة",
            "Close": "غلق",
            "Close Header and Footer": "إغلاق الرأس والتذييل",
            "Close header and footer view": "إغلاق عرض الرأس والتذييل",
            "Link to the previous sections header and footer": "الارتباط برأس وتذييل الأقسام السابقة",
            "Picture Format": "تنسيق الصورة",
            "Picture Tools": "أدوات الصور",
            "Adjust image width": "ضبط عرض الصورة",
            "Adjust image height": "ضبط ارتفاع الصورة",
            "Maintain aspect ratio when resizing": "الحفاظ على نسبة العرض إلى الارتفاع عند تغيير الحجم",
            "Add descriptive text for screen readers": "إضافة نص وصفي لقارئات الشاشة",
            "Enter alternate text": "إدخال نص بديل",
            "Adjust image width and height": "ضبط عرض الصورة وارتفاعها",
            "Page Break": "فاصل الصفحة",
            "Pages": "الصفحات",
            "References": "مراجع",
            "Margins": "الهوامش",
            "Narrow": "ضيق",
            "Moderate": "المعتدل",
            "Wide": "واسع",
            "Custom Margins": "الهوامش المخصصة",
            "Orientation": "اتجاه",
            "Portrait": "صوره",
            "Landscape": "المنظر الطبيعي",
            "Size": "حجم",
            "Letter": "رسالة",
            "Legal": "قانوني",
            "Executive": "تنفيذي",
            "A4": "أ 4",
            "A5": "أ 5",
            "Custom Size": "حجم مخصص",
            "One": "واحد",
            "Two": "اثنان",
            "Three": "تلاتة",
            "More Columns": "المزيد من الأعمدة",
            "Breaks": "فواصل",
            "Left Indent": "المسافة البادئة اليسرى",
            "Right Indent": "المسافة البادئة اليمنى",
            "Before Spacing": "قبل التباعد",
            "After Spacing": "بعد التباعد",
            "Layout": "تخطيط",
            "Footnotes": "الحواشي السفليه",
            "Update Table": "تحديث الجدول",
            "PageSetup": "إعداد الصفحة",
            "Indent": "سنن",
            "Spacing": "تباعد",
            "CustomPageSize": "حجم مخصص ...",
            "MoreColumns": "المزيد من الأعمدة...",
            "PageBreak": "فاصل الصفحة",
            "ColumnBreak": "فاصل العمود",
            "Before": "قبل",
            "After": "بعد",
            "LeftIndent": "يسار",
            "LeftIndentTooltip": "تعيين المسافة البادئة اليسرى للفقرة",
            "RightIndent": "يمين",
            "RightIndentTooltip": "تعيين المسافة البادئة اليمنى للفقرة",
            "SpacingBefore": "قبل",
            "SpacingBeforeTooltip": "تعيين التباعد قبل الفقرة",
            "SpacingAfter": "بعد",
            "SpacingAfterTooltip": "تعيين التباعد بعد الفقرة",
            "ParagraphDialogTooltip": "فتح مربع الحوار فقرة",
            "Bookmarks": "الاشارات المرجعيه",
            "Insert Bookmark": "إدراج إشارة مرجعية",
            "All Bookmarks": "جميع الإشارات المرجعية",
            "Show Bookmarks": "إظهار الإشارات المرجعية",
            "Create or manage bookmarks in your document": "إنشاء الإشارات المرجعية أو إدارتها في المستند",
            "View all bookmarks in the document": "عرض جميع الإشارات المرجعية في المستند",
            "Toggle visibility of bookmark markers in the document": "تبديل رؤية علامات الإشارات المرجعية في المستند",
            "New Comment": "تعليق جديد",
            "Add a comment about the current selection": "إضافة تعليق حول التحديد الحالي",
            "Insert a table of contents": "إدراج جدول محتويات",
            "Insert a page break at the current position": "إدراج فاصل صفحة في الموضع الحالي",
            "Review": "استعراض",
            "Previous": "سابق",
            "Next": "مقبل",
            "Delete": "حذف",
            "Delete All": "حذف الكل",
            "Show Comments": "إظهار التعليقات",
            "Tracking": "تتبع",
            "Accept All": "قبول الكل",
            "Reject All": "رفض الكل",
            "Protect": "حمى",
            "Protect Document": "حماية المستند",
            "Read Only": "للقراءة فقط",
            "Encrypt with Password": "التشفير بكلمة مرور",
            "Restrict Access": "تقييد الوصول",
            "Mark as Final": "وضع علامة كنهائي",
            "Insert a comment at the cursor position": "إدراج تعليق في موضع المؤشر",
            "Go to the previous comment": "انتقل إلى التعليق السابق",
            "Go to the next comment": "انتقل إلى التعليق التالي",
            "Delete comments": "حذف التعليقات",
            "Show or hide comments": "إظهار التعليقات أو إخفاؤها",
            "Track changes while editing the document": "تعقب التغييرات أثناء تحرير المستند",
            "Accept all changes in the document": "قبول جميع التغييرات في المستند",
            "Reject all changes in the document": "رفض جميع التغييرات في المستند",
            "Control what types of changes can be made to the document": "التحكم في أنواع التغييرات التي يمكن إجراؤها على المستند",
            "Make the document read-only": "جعل المستند للقراءة فقط",
            "Restrict how users can edit the document": "تقييد كيفية قيام المستخدمين بتحرير المستند",
            "Print Layout": "تخطيط الطباعة",
            "Web Layout": "تخطيط الويب",
            "Toggle document to read only mode": "تبديل المستند إلى وضع القراءة فقط",
            "Navigation Pane": "جزء التنقل",
            "Show or hide the navigation pane": "إظهار جزء التنقل أو إخفاؤه",
            "Grow Font Size": "زيادة حجم الخط (Ctrl+Shift+>)",
            "Shrink Font Size": "تقليص حجم الخط (Ctrl+Shift+<)",
            "Shading": "تظليل",
            "Select": "اختار",
            "Row": "صف",
            "Rows & Columns": "الصفوف والأعمدة",
            "Table Layout": "تخطيط الجدول",
            "Row Above": "الصف أعلاه",
            "Row Below": "الصف أدناه",
            "Column Left": "العمود الأيسر",
            "Column Right": "العمود الأيمن",
            "Cut Tooltip": "قص (Ctrl + X)",
            "Copy Tooltip": "نسخ (Ctrl+C)",
            "100%": "100%",
            "Zoom your document to 100%": "تكبير المستند إلى 100٪",
            "Office2003Default": "Office 2003 الافتراضي",
            "CustomMargins": "هوامش مخصصة...",
            "MarginsTooltip": "اختيار إعدادات هامش الصفحة للمستند",
            "Indent Left": "المسافة البادئة لليسار",
            "Indent Right": "المسافة البادئة اليمنى",
            "Spacing Before": "التباعد قبل",
            "Spacing After": "التباعد بعد",
            "Set the distance between paragraph and left margin": "تعيين المسافة بين الفقرة والهامش الأيسر",
            "Set the distance between paragraph and right margin": "تعيين المسافة بين الفقرة والهامش الأيمن",
            "Set the spacing before the paragraph": "تعيين التباعد قبل الفقرة",
            "Set the spacing after the paragraph": "تعيين التباعد بعد الفقرة",
            "Table Design": "تصميم الجدول",
            "Properties": "خصائص",
            "Show the Table Properties dialog": "إظهار مربع الحوار خصائص الجدول",
            "Alt Text": "النص البديل",
            "Alternative Text": "النص البديل",
            "Enter alt text for this image": "أدخل نصا بديلا لهذه الصورة",
            "Apply": "طبق",
            "Accessibility": "امكانيه الوصول",
            "Add alternative text to the image for accessibility": "إضافة نص بديل إلى الصورة لإمكانية الوصول",
            "File": "ملف",
            "Export": "تصدير",
            "Print": "طبع",
            "Syncfusion Document Text (*.sfdt)": "نص مستند التزامن (*.sfdt)",
            "Word Document (*.docx)": "مستند كلمة (*.docx)",
            "Word Template (*.dotx)": "قالب كلمة (*.dotx)",
            "Plain Text (*.txt)": "نص عادي (*.txt)",
            "Unsupported format": "تنسيق غير مدعوم",
            "BackstageView": "عرض وراء الكواليس",
            "BackstageHeader": "إدارة الملفات",
            "BackstageClose": "غلق",
            "Developer": "المطور",
            "Insert form fields": "إدراج حقول النموذج",
            "Controls": "عناصر التحكم",
            "Insert content controls": "إدراج عناصر تحكم المحتوى",
            "Mapping": "تعيين",
            "Restrict editing": "تقييد التحرير",
            "More Paragraph Options": "المزيد من خيارات الفقرة",
            "More Font Options": "المزيد من خيارات الخطوط",
            "Show/Hide Marks": "إظهار / إخفاء العلامات",
            "All Borders": "جميع الحدود",
            "Outside Borders": "خارج الحدود",
            "Inside Borders": "داخل الحدود",
            "Top Border": "الحدود العلوية",
            "Bottom Border": "الحد السفلي",
            "Left Border": "الحدود اليسرى",
            "Right Border": "الحدود اليمنى",
            "Inside Horizontal Border": "داخل الحدود الأفقية",
            "Inside Vertical Border": "داخل الحدود العمودية",
            "Table Borders": "حدود الجدول",
            "Border Color": "لون الحدود",
            "Border Width": "عرض الحدود",
            "px": "مقصف",
            "SizeTooltip": "اختر حجم ورق للمستند",
            "OrientationTooltip": "اختر اتجاه الصفحة",
            "ColumnsTooltip": "اختر أعمدة المستند",
            "Insert rows and columns": "إدراج صفوف وأعمدة",
            "Select the table": "حدد الجدول",
            "Delete the table": "حذف الجدول",
            "Cell Properties": "خصائص الخلية",
            "Show or hide the rulers": "إظهار المساطر أو إخفاؤها",
            "Show or hide bookmark markers": "إظهار العلامات المرجعية أو إخفاؤها"
        },
        'colorpicker': {
            'Apply': 'تطبيق',
            'Cancel': 'إلغاء الأمر',
            'ModeSwitcher': 'مفتاح كهربائي الوضع'
        }
    }
});

/**
 * Default document editor sample
 */
(window as any).default = (): void => {
    loadCultureFiles();
    let hostUrl: string = 'https://services.syncfusion.com/js/production/api/documenteditor/';

    let container: DocumentEditorContainer = new DocumentEditorContainer({
        serviceUrl: hostUrl, toolbarMode: 'Ribbon', enableToolbar: true,
        height: '590px', enableRtl: true, locale: 'ar-AE', documentEditorSettings: { showRuler: true }
    });
    DocumentEditorContainer.Inject(Toolbar, Ribbon);
    container.appendTo('#container');

    let titleBar: TitleBar = new TitleBar(document.getElementById('documenteditor_titlebar'), container.documentEditor, true, true);
    container.documentEditor.open(JSON.stringify((<any>data)));
    container.documentEditor.documentName = 'الشروع';
    titleBar.updateDocumentTitle();

    container.documentChange = (): void => {
        titleBar.updateDocumentTitle();
        container.documentEditor.focusIn();
    };
    titleBar.initializeRibbonSwitch(container);
    titleBar.showButtons(false);
};
